export default {
products: [
{
     _id: '1',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/im1.jpg',
      rating: 4.5,
      numReview: 23,
      countInStock: 0,
},
{
      _id: '2',
      name:'best shirt',
      category: 'Shirts',
      image: '/images/im2.jpg',
      rating: 4.5,
      numReview: 110,
      countInStock: 8,
},
{
      _id: '3',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/im3.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 9,
},
{
      _id: '4',
      name:'first shirt',
      category: 'Shirts',
      image: '/images/im4.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 10,
},
{
      _id: '5',
      name:'nice shirt',
      category: 'Shirts',
      image: '/images/im5.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 11,
},
{
      _id: '6',
      name:'small shirt',
      category: 'Shirts',
      image: '/images/im6.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 12,
},
{
      _id: '7',
      name:'large shirt',
      category: 'Shirts',
      image: '/images/im7.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 13,
},
{
      _id:'8',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/im8.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 14,
},
{
      _id: '9',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/im9.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 15,
},
{
      _id: '9',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/img-10.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 15,
},
{
      _id: '9',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/img-11.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 15,
},
{
      _id: '9',
      name:'Slim shirt',
      category: 'Shirts',
      image: '/images/img.jpg',
      rating: 4.5,
      numReview: 101,
      countInStock: 15,
},
]
}